/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void stepSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:stepSlider:281827:
  bot1.changeStep(stepSlider.getValueF());
  bot2.changeStep(stepSlider.getValueF());
} //_CODE_:stepSlider:281827:

public void restart(GButton source, GEvent event) { //_CODE_:restartToggle:531051:
  f = 0;
  bot1.restart();
  bot2.restart();
} //_CODE_:restartToggle:531051:

public void playpausePressed(GButton source, GEvent event) { //_CODE_:playpause:761232:
  bot1.pausePlay();
  bot2.pausePlay();
} //_CODE_:playpause:761232:

public void xSliderChange(GCustomSlider source, GEvent event) { //_CODE_:xSlider:594826:
  bot1.changeX(xSlider.getValueF());
  bot2.changeX(xSlider.getValueF());
} //_CODE_:xSlider:594826:

public void bot1SpeedSlider_Changed(GCustomSlider source, GEvent event) { //_CODE_:bot1SpeedSlider:689719:
  bot1.changeSpeed(bot1SpeedSlider.getValueF());
  bot2.needsRestart = true;
} //_CODE_:bot1SpeedSlider:689719:

public void bot2SpeedSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:bot2SpeedSlider:313686:
  bot2.changeSpeed(bot2SpeedSlider.getValueF());
  bot1.needsRestart = true;
} //_CODE_:bot2SpeedSlider:313686:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  stepSlider = new GCustomSlider(this, 1012, 650, 178, 68, "grey_blue");
  stepSlider.setShowValue(true);
  stepSlider.setShowLimits(true);
  stepSlider.setLimits(25.0, 1.0, 50.0);
  stepSlider.setShowTicks(true);
  stepSlider.setNumberFormat(G4P.DECIMAL, 2);
  stepSlider.setLocalColorScheme(GCScheme.SCHEME_13);
  stepSlider.setOpaque(false);
  stepSlider.addEventHandler(this, "stepSliderChanged");
  restartToggle = new GButton(this, 1107, 748, 80, 30);
  restartToggle.setText("RESTART");
  restartToggle.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  restartToggle.addEventHandler(this, "restart");
  playpause = new GButton(this, 1017, 748, 80, 30);
  playpause.setText("PLAY/PAUSE");
  playpause.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  playpause.addEventHandler(this, "playpausePressed");
  xSlider = new GCustomSlider(this, 1012, 540, 178, 68, "grey_blue");
  xSlider.setShowValue(true);
  xSlider.setShowLimits(true);
  xSlider.setLimits(500.0, 0.0, 1000.0);
  xSlider.setNumberFormat(G4P.DECIMAL, 2);
  xSlider.setLocalColorScheme(GCScheme.SCHEME_13);
  xSlider.setOpaque(false);
  xSlider.addEventHandler(this, "xSliderChange");
  bot1SpeedSlider = new GCustomSlider(this, 1012, 170, 178, 42, "grey_blue");
  bot1SpeedSlider.setShowValue(true);
  bot1SpeedSlider.setShowLimits(true);
  bot1SpeedSlider.setTextOrientation(G4P.BLUE_SCHEME);
  bot1SpeedSlider.setLimits(10.0, 1.0, 100.0);
  bot1SpeedSlider.setShowTicks(true);
  bot1SpeedSlider.setNumberFormat(G4P.DECIMAL, 2);
  bot1SpeedSlider.setLocalColorScheme(GCScheme.SCHEME_13);
  bot1SpeedSlider.setOpaque(false);
  bot1SpeedSlider.addEventHandler(this, "bot1SpeedSlider_Changed");
  bot2SpeedSlider = new GCustomSlider(this, 1012, 370, 178, 42, "grey_blue");
  bot2SpeedSlider.setShowValue(true);
  bot2SpeedSlider.setShowLimits(true);
  bot2SpeedSlider.setLimits(10.0, 1.0, 100.0);
  bot2SpeedSlider.setShowTicks(true);
  bot2SpeedSlider.setNumberFormat(G4P.DECIMAL, 2);
  bot2SpeedSlider.setLocalColorScheme(GCScheme.SCHEME_13);
  bot2SpeedSlider.setOpaque(false);
  bot2SpeedSlider.addEventHandler(this, "bot2SpeedSliderChanged");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider stepSlider; 
GButton restartToggle; 
GButton playpause; 
GCustomSlider xSlider; 
GCustomSlider bot1SpeedSlider; 
GCustomSlider bot2SpeedSlider; 
